prefix : <http://example.org/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix dbp: <http://dbpedia.org/property/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

construct { 
  :Elixir
    :name     ?name ;
    :homepage ?homepage ;
    :license  ?license ;
    :creator  ?creator .
}
where  { 
  <http://dbpedia.org/resource/Elixir_(programming_language)> 
    foaf:name     ?name ;
    foaf:homepage ?homepage ;
    dbp:creator   ?creator ;
    dbo:license   ?license .
}
