prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
construct
{
  ?s ?p ?o
}
where {
  bind (<http://dbpedia.org/resource/London> as ?s)
  ?s ?p ?o .
  filter ( !(!isiri(?o) && datatype(?o) = rdf:langString && langMatches( lang(?o), "" )) )
}
